/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Surah = IDL.Record({
  'ayahCount' : IDL.Nat,
  'urduName' : IDL.Text,
  'audioUrl' : IDL.Text,
  'transliteration' : IDL.Text,
  'arabicName' : IDL.Text,
  'number' : IDL.Nat,
});
export const Ayah = IDL.Record({
  'startingTime' : IDL.Nat,
  'urduTranslation' : IDL.Text,
  'arabicText' : IDL.Text,
  'number' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllSurahs' : IDL.Func([], [IDL.Vec(Surah)], ['query']),
  'getAyahsForSurah' : IDL.Func([IDL.Nat], [IDL.Vec(Ayah)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Surah = IDL.Record({
    'ayahCount' : IDL.Nat,
    'urduName' : IDL.Text,
    'audioUrl' : IDL.Text,
    'transliteration' : IDL.Text,
    'arabicName' : IDL.Text,
    'number' : IDL.Nat,
  });
  const Ayah = IDL.Record({
    'startingTime' : IDL.Nat,
    'urduTranslation' : IDL.Text,
    'arabicText' : IDL.Text,
    'number' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllSurahs' : IDL.Func([], [IDL.Vec(Surah)], ['query']),
    'getAyahsForSurah' : IDL.Func([IDL.Nat], [IDL.Vec(Ayah)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };